// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1alpha1/current_user.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ResetPasswordRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResetPasswordRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetPasswordRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResetPasswordRequestMultiError, or nil if none found.
func (m *ResetPasswordRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetPasswordRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetOldPassword()) < 1 {
		err := ResetPasswordRequestValidationError{
			field:  "OldPassword",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetNewPassword()) < 1 {
		err := ResetPasswordRequestValidationError{
			field:  "NewPassword",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ResetPasswordRequestMultiError(errors)
	}

	return nil
}

// ResetPasswordRequestMultiError is an error wrapping multiple validation
// errors returned by ResetPasswordRequest.ValidateAll() if the designated
// constraints aren't met.
type ResetPasswordRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetPasswordRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetPasswordRequestMultiError) AllErrors() []error { return m }

// ResetPasswordRequestValidationError is the validation error returned by
// ResetPasswordRequest.Validate if the designated constraints aren't met.
type ResetPasswordRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetPasswordRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetPasswordRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetPasswordRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetPasswordRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetPasswordRequestValidationError) ErrorName() string {
	return "ResetPasswordRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResetPasswordRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetPasswordRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetPasswordRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetPasswordRequestValidationError{}

// Validate checks the field values on ResetPasswordResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResetPasswordResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetPasswordResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResetPasswordResponseMultiError, or nil if none found.
func (m *ResetPasswordResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetPasswordResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ResetPasswordResponseMultiError(errors)
	}

	return nil
}

// ResetPasswordResponseMultiError is an error wrapping multiple validation
// errors returned by ResetPasswordResponse.ValidateAll() if the designated
// constraints aren't met.
type ResetPasswordResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetPasswordResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetPasswordResponseMultiError) AllErrors() []error { return m }

// ResetPasswordResponseValidationError is the validation error returned by
// ResetPasswordResponse.Validate if the designated constraints aren't met.
type ResetPasswordResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetPasswordResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetPasswordResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetPasswordResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetPasswordResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetPasswordResponseValidationError) ErrorName() string {
	return "ResetPasswordResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ResetPasswordResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetPasswordResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetPasswordResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetPasswordResponseValidationError{}

// Validate checks the field values on ListAccessTokensRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAccessTokensRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAccessTokensRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAccessTokensRequestMultiError, or nil if none found.
func (m *ListAccessTokensRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAccessTokensRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListAccessTokensRequestMultiError(errors)
	}

	return nil
}

// ListAccessTokensRequestMultiError is an error wrapping multiple validation
// errors returned by ListAccessTokensRequest.ValidateAll() if the designated
// constraints aren't met.
type ListAccessTokensRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAccessTokensRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAccessTokensRequestMultiError) AllErrors() []error { return m }

// ListAccessTokensRequestValidationError is the validation error returned by
// ListAccessTokensRequest.Validate if the designated constraints aren't met.
type ListAccessTokensRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAccessTokensRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAccessTokensRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAccessTokensRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAccessTokensRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAccessTokensRequestValidationError) ErrorName() string {
	return "ListAccessTokensRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListAccessTokensRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAccessTokensRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAccessTokensRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAccessTokensRequestValidationError{}

// Validate checks the field values on ListAccessTokensResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAccessTokensResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAccessTokensResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAccessTokensResponseMultiError, or nil if none found.
func (m *ListAccessTokensResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAccessTokensResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAccessTokensResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAccessTokensResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAccessTokensResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListAccessTokensResponseMultiError(errors)
	}

	return nil
}

// ListAccessTokensResponseMultiError is an error wrapping multiple validation
// errors returned by ListAccessTokensResponse.ValidateAll() if the designated
// constraints aren't met.
type ListAccessTokensResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAccessTokensResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAccessTokensResponseMultiError) AllErrors() []error { return m }

// ListAccessTokensResponseValidationError is the validation error returned by
// ListAccessTokensResponse.Validate if the designated constraints aren't met.
type ListAccessTokensResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAccessTokensResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAccessTokensResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAccessTokensResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAccessTokensResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAccessTokensResponseValidationError) ErrorName() string {
	return "ListAccessTokensResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListAccessTokensResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAccessTokensResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAccessTokensResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAccessTokensResponseValidationError{}

// Validate checks the field values on AccessToken with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AccessToken) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AccessToken with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AccessTokenMultiError, or
// nil if none found.
func (m *AccessToken) ValidateAll() error {
	return m.validate(true)
}

func (m *AccessToken) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for ExpiredAt

	if len(errors) > 0 {
		return AccessTokenMultiError(errors)
	}

	return nil
}

// AccessTokenMultiError is an error wrapping multiple validation errors
// returned by AccessToken.ValidateAll() if the designated constraints aren't met.
type AccessTokenMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AccessTokenMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AccessTokenMultiError) AllErrors() []error { return m }

// AccessTokenValidationError is the validation error returned by
// AccessToken.Validate if the designated constraints aren't met.
type AccessTokenValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessTokenValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessTokenValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessTokenValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessTokenValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessTokenValidationError) ErrorName() string { return "AccessTokenValidationError" }

// Error satisfies the builtin error interface
func (e AccessTokenValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessToken.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessTokenValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessTokenValidationError{}

// Validate checks the field values on CreateAccessTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAccessTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAccessTokenRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAccessTokenRequestMultiError, or nil if none found.
func (m *CreateAccessTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAccessTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 125 {
		err := CreateAccessTokenRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 125 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ExpireAt

	if len(errors) > 0 {
		return CreateAccessTokenRequestMultiError(errors)
	}

	return nil
}

// CreateAccessTokenRequestMultiError is an error wrapping multiple validation
// errors returned by CreateAccessTokenRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateAccessTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAccessTokenRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAccessTokenRequestMultiError) AllErrors() []error { return m }

// CreateAccessTokenRequestValidationError is the validation error returned by
// CreateAccessTokenRequest.Validate if the designated constraints aren't met.
type CreateAccessTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAccessTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAccessTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAccessTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAccessTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAccessTokenRequestValidationError) ErrorName() string {
	return "CreateAccessTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAccessTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAccessTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAccessTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAccessTokenRequestValidationError{}

// Validate checks the field values on CreateAccessTokenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAccessTokenResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAccessTokenResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAccessTokenResponseMultiError, or nil if none found.
func (m *CreateAccessTokenResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAccessTokenResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return CreateAccessTokenResponseMultiError(errors)
	}

	return nil
}

// CreateAccessTokenResponseMultiError is an error wrapping multiple validation
// errors returned by CreateAccessTokenResponse.ValidateAll() if the
// designated constraints aren't met.
type CreateAccessTokenResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAccessTokenResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAccessTokenResponseMultiError) AllErrors() []error { return m }

// CreateAccessTokenResponseValidationError is the validation error returned by
// CreateAccessTokenResponse.Validate if the designated constraints aren't met.
type CreateAccessTokenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAccessTokenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAccessTokenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAccessTokenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAccessTokenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAccessTokenResponseValidationError) ErrorName() string {
	return "CreateAccessTokenResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAccessTokenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAccessTokenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAccessTokenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAccessTokenResponseValidationError{}

// Validate checks the field values on DeleteAccessTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteAccessTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteAccessTokenRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteAccessTokenRequestMultiError, or nil if none found.
func (m *DeleteAccessTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteAccessTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteAccessTokenRequestMultiError(errors)
	}

	return nil
}

// DeleteAccessTokenRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteAccessTokenRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteAccessTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteAccessTokenRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteAccessTokenRequestMultiError) AllErrors() []error { return m }

// DeleteAccessTokenRequestValidationError is the validation error returned by
// DeleteAccessTokenRequest.Validate if the designated constraints aren't met.
type DeleteAccessTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteAccessTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteAccessTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteAccessTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteAccessTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteAccessTokenRequestValidationError) ErrorName() string {
	return "DeleteAccessTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteAccessTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteAccessTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteAccessTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteAccessTokenRequestValidationError{}

// Validate checks the field values on DeleteAccessTokenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteAccessTokenResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteAccessTokenResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteAccessTokenResponseMultiError, or nil if none found.
func (m *DeleteAccessTokenResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteAccessTokenResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteAccessTokenResponseMultiError(errors)
	}

	return nil
}

// DeleteAccessTokenResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteAccessTokenResponse.ValidateAll() if the
// designated constraints aren't met.
type DeleteAccessTokenResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteAccessTokenResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteAccessTokenResponseMultiError) AllErrors() []error { return m }

// DeleteAccessTokenResponseValidationError is the validation error returned by
// DeleteAccessTokenResponse.Validate if the designated constraints aren't met.
type DeleteAccessTokenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteAccessTokenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteAccessTokenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteAccessTokenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteAccessTokenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteAccessTokenResponseValidationError) ErrorName() string {
	return "DeleteAccessTokenResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteAccessTokenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteAccessTokenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteAccessTokenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteAccessTokenResponseValidationError{}

// Validate checks the field values on GetProjectRolesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetProjectRolesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProjectRolesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetProjectRolesRequestMultiError, or nil if none found.
func (m *GetProjectRolesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProjectRolesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetProjectRolesRequestMultiError(errors)
	}

	return nil
}

// GetProjectRolesRequestMultiError is an error wrapping multiple validation
// errors returned by GetProjectRolesRequest.ValidateAll() if the designated
// constraints aren't met.
type GetProjectRolesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProjectRolesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProjectRolesRequestMultiError) AllErrors() []error { return m }

// GetProjectRolesRequestValidationError is the validation error returned by
// GetProjectRolesRequest.Validate if the designated constraints aren't met.
type GetProjectRolesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProjectRolesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProjectRolesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProjectRolesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProjectRolesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProjectRolesRequestValidationError) ErrorName() string {
	return "GetProjectRolesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetProjectRolesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProjectRolesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProjectRolesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProjectRolesRequestValidationError{}

// Validate checks the field values on GetProjectRolesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetProjectRolesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProjectRolesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetProjectRolesResponseMultiError, or nil if none found.
func (m *GetProjectRolesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProjectRolesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectRoles

	if len(errors) > 0 {
		return GetProjectRolesResponseMultiError(errors)
	}

	return nil
}

// GetProjectRolesResponseMultiError is an error wrapping multiple validation
// errors returned by GetProjectRolesResponse.ValidateAll() if the designated
// constraints aren't met.
type GetProjectRolesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProjectRolesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProjectRolesResponseMultiError) AllErrors() []error { return m }

// GetProjectRolesResponseValidationError is the validation error returned by
// GetProjectRolesResponse.Validate if the designated constraints aren't met.
type GetProjectRolesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProjectRolesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProjectRolesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProjectRolesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProjectRolesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProjectRolesResponseValidationError) ErrorName() string {
	return "GetProjectRolesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetProjectRolesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProjectRolesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProjectRolesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProjectRolesResponseValidationError{}

// Validate checks the field values on GetCurrentUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCurrentUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCurrentUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCurrentUserRequestMultiError, or nil if none found.
func (m *GetCurrentUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCurrentUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetCurrentUserRequestMultiError(errors)
	}

	return nil
}

// GetCurrentUserRequestMultiError is an error wrapping multiple validation
// errors returned by GetCurrentUserRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCurrentUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCurrentUserRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCurrentUserRequestMultiError) AllErrors() []error { return m }

// GetCurrentUserRequestValidationError is the validation error returned by
// GetCurrentUserRequest.Validate if the designated constraints aren't met.
type GetCurrentUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCurrentUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCurrentUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCurrentUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCurrentUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCurrentUserRequestValidationError) ErrorName() string {
	return "GetCurrentUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCurrentUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCurrentUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCurrentUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCurrentUserRequestValidationError{}

// Validate checks the field values on GetCurrentUserResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCurrentUserResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCurrentUserResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCurrentUserResponseMultiError, or nil if none found.
func (m *GetCurrentUserResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCurrentUserResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Username

	// no validation rules for IsAdmin

	if len(errors) > 0 {
		return GetCurrentUserResponseMultiError(errors)
	}

	return nil
}

// GetCurrentUserResponseMultiError is an error wrapping multiple validation
// errors returned by GetCurrentUserResponse.ValidateAll() if the designated
// constraints aren't met.
type GetCurrentUserResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCurrentUserResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCurrentUserResponseMultiError) AllErrors() []error { return m }

// GetCurrentUserResponseValidationError is the validation error returned by
// GetCurrentUserResponse.Validate if the designated constraints aren't met.
type GetCurrentUserResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCurrentUserResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCurrentUserResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCurrentUserResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCurrentUserResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCurrentUserResponseValidationError) ErrorName() string {
	return "GetCurrentUserResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetCurrentUserResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCurrentUserResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCurrentUserResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCurrentUserResponseValidationError{}
