// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/current_user.proto

package v1alpha1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{0}
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{1}
}

type ListAccessTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessTokensRequest) Reset() {
	*x = ListAccessTokensRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessTokensRequest) ProtoMessage() {}

func (x *ListAccessTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessTokensRequest.ProtoReflect.Descriptor instead.
func (*ListAccessTokensRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{2}
}

type ListAccessTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AccessToken         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessTokensResponse) Reset() {
	*x = ListAccessTokensResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessTokensResponse) ProtoMessage() {}

func (x *ListAccessTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessTokensResponse.ProtoReflect.Descriptor instead.
func (*ListAccessTokensResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListAccessTokensResponse) GetItems() []*AccessToken {
	if x != nil {
		return x.Items
	}
	return nil
}

type AccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiredAt     string                 `protobuf:"bytes,5,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{4}
}

func (x *AccessToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessToken) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *AccessToken) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AccessToken) GetExpiredAt() string {
	if x != nil {
		return x.ExpiredAt
	}
	return ""
}

type CreateAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExpiredAt     string                 `protobuf:"bytes,2,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessTokenRequest) Reset() {
	*x = CreateAccessTokenRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessTokenRequest) ProtoMessage() {}

func (x *CreateAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccessTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccessTokenRequest) GetExpiredAt() string {
	if x != nil {
		return x.ExpiredAt
	}
	return ""
}

type CreateAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessTokenResponse) Reset() {
	*x = CreateAccessTokenResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessTokenResponse) ProtoMessage() {}

func (x *CreateAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{6}
}

type DeleteAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccessTokenRequest) Reset() {
	*x = DeleteAccessTokenRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccessTokenRequest) ProtoMessage() {}

func (x *DeleteAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAccessTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccessTokenResponse) Reset() {
	*x = DeleteAccessTokenResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccessTokenResponse) ProtoMessage() {}

func (x *DeleteAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{8}
}

var File_v1alpha1_current_user_proto protoreflect.FileDescriptor

const file_v1alpha1_current_user_proto_rawDesc = "" +
	"\n" +
	"\x1bv1alpha1/current_user.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\";\n" +
	"\x14ResetPasswordRequest\x12#\n" +
	"\bpassword\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bpassword\"\x17\n" +
	"\x15ResetPasswordResponse\"\x19\n" +
	"\x17ListAccessTokensRequest\"Q\n" +
	"\x18ListAccessTokensResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.matrixhub.v1alpha1.AccessTokenR\x05items\"\x8e\x01\n" +
	"\vAccessToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x05 \x01(\tR\texpiredAt\"X\n" +
	"\x18CreateAccessTokenRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18}R\x04name\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x02 \x01(\tR\texpiredAt\"\x1b\n" +
	"\x19CreateAccessTokenResponse\"4\n" +
	"\x18DeleteAccessTokenRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"\x1b\n" +
	"\x19DeleteAccessTokenResponse2\xa0\x05\n" +
	"\vCurrentUser\x12\x9a\x01\n" +
	"\rResetPassword\x12(.matrixhub.v1alpha1.ResetPasswordRequest\x1a).matrixhub.v1alpha1.ResetPasswordResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/v1alpha1/current-user/reset-password\x12\x9f\x01\n" +
	"\x10ListAccessTokens\x12+.matrixhub.v1alpha1.ListAccessTokensRequest\x1a,.matrixhub.v1alpha1.ListAccessTokensResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/v1alpha1/current-user/access-tokens\x12\xa6\x01\n" +
	"\x11CreateAccessToken\x12,.matrixhub.v1alpha1.CreateAccessTokenRequest\x1a-.matrixhub.v1alpha1.CreateAccessTokenResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/apis/v1alpha1/current-user/access-tokens\x12\xa8\x01\n" +
	"\x11DeleteAccessToken\x12,.matrixhub.v1alpha1.DeleteAccessTokenRequest\x1a-.matrixhub.v1alpha1.DeleteAccessTokenResponse\"6\x82\xd3\xe4\x93\x020*./apis/v1alpha1/current-user/access-tokens/{id}B<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_current_user_proto_rawDescOnce sync.Once
	file_v1alpha1_current_user_proto_rawDescData []byte
)

func file_v1alpha1_current_user_proto_rawDescGZIP() []byte {
	file_v1alpha1_current_user_proto_rawDescOnce.Do(func() {
		file_v1alpha1_current_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_current_user_proto_rawDesc), len(file_v1alpha1_current_user_proto_rawDesc)))
	})
	return file_v1alpha1_current_user_proto_rawDescData
}

var file_v1alpha1_current_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1alpha1_current_user_proto_goTypes = []any{
	(*ResetPasswordRequest)(nil),      // 0: matrixhub.v1alpha1.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),     // 1: matrixhub.v1alpha1.ResetPasswordResponse
	(*ListAccessTokensRequest)(nil),   // 2: matrixhub.v1alpha1.ListAccessTokensRequest
	(*ListAccessTokensResponse)(nil),  // 3: matrixhub.v1alpha1.ListAccessTokensResponse
	(*AccessToken)(nil),               // 4: matrixhub.v1alpha1.AccessToken
	(*CreateAccessTokenRequest)(nil),  // 5: matrixhub.v1alpha1.CreateAccessTokenRequest
	(*CreateAccessTokenResponse)(nil), // 6: matrixhub.v1alpha1.CreateAccessTokenResponse
	(*DeleteAccessTokenRequest)(nil),  // 7: matrixhub.v1alpha1.DeleteAccessTokenRequest
	(*DeleteAccessTokenResponse)(nil), // 8: matrixhub.v1alpha1.DeleteAccessTokenResponse
}
var file_v1alpha1_current_user_proto_depIdxs = []int32{
	4, // 0: matrixhub.v1alpha1.ListAccessTokensResponse.items:type_name -> matrixhub.v1alpha1.AccessToken
	0, // 1: matrixhub.v1alpha1.CurrentUser.ResetPassword:input_type -> matrixhub.v1alpha1.ResetPasswordRequest
	2, // 2: matrixhub.v1alpha1.CurrentUser.ListAccessTokens:input_type -> matrixhub.v1alpha1.ListAccessTokensRequest
	5, // 3: matrixhub.v1alpha1.CurrentUser.CreateAccessToken:input_type -> matrixhub.v1alpha1.CreateAccessTokenRequest
	7, // 4: matrixhub.v1alpha1.CurrentUser.DeleteAccessToken:input_type -> matrixhub.v1alpha1.DeleteAccessTokenRequest
	1, // 5: matrixhub.v1alpha1.CurrentUser.ResetPassword:output_type -> matrixhub.v1alpha1.ResetPasswordResponse
	3, // 6: matrixhub.v1alpha1.CurrentUser.ListAccessTokens:output_type -> matrixhub.v1alpha1.ListAccessTokensResponse
	6, // 7: matrixhub.v1alpha1.CurrentUser.CreateAccessToken:output_type -> matrixhub.v1alpha1.CreateAccessTokenResponse
	8, // 8: matrixhub.v1alpha1.CurrentUser.DeleteAccessToken:output_type -> matrixhub.v1alpha1.DeleteAccessTokenResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1alpha1_current_user_proto_init() }
func file_v1alpha1_current_user_proto_init() {
	if File_v1alpha1_current_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_current_user_proto_rawDesc), len(file_v1alpha1_current_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_current_user_proto_goTypes,
		DependencyIndexes: file_v1alpha1_current_user_proto_depIdxs,
		MessageInfos:      file_v1alpha1_current_user_proto_msgTypes,
	}.Build()
	File_v1alpha1_current_user_proto = out.File
	file_v1alpha1_current_user_proto_goTypes = nil
	file_v1alpha1_current_user_proto_depIdxs = nil
}
