// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: v1alpha1/replication.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Replication_ListReplications_FullMethodName           = "/matrixhub.v1alpha1.Replication/ListReplications"
	Replication_CreateReplication_FullMethodName          = "/matrixhub.v1alpha1.Replication/CreateReplication"
	Replication_UpdateReplication_FullMethodName          = "/matrixhub.v1alpha1.Replication/UpdateReplication"
	Replication_DeleteReplication_FullMethodName          = "/matrixhub.v1alpha1.Replication/DeleteReplication"
	Replication_CreateReplicationExecution_FullMethodName = "/matrixhub.v1alpha1.Replication/CreateReplicationExecution"
	Replication_ListReplicationExecutions_FullMethodName  = "/matrixhub.v1alpha1.Replication/ListReplicationExecutions"
	Replication_StopReplicationExecution_FullMethodName   = "/matrixhub.v1alpha1.Replication/StopReplicationExecution"
)

// ReplicationClient is the client API for Replication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationClient interface {
	// ListReplications lists all replications.
	ListReplications(ctx context.Context, in *ListReplicationsRequest, opts ...grpc.CallOption) (*ListReplicationsResponse, error)
	// CreateReplication creates a new replication.
	CreateReplication(ctx context.Context, in *CreateReplicationRequest, opts ...grpc.CallOption) (*CreateReplicationResponse, error)
	// UpdateReplication updates a replication.
	UpdateReplication(ctx context.Context, in *UpdateReplicationRequest, opts ...grpc.CallOption) (*UpdateReplicationResponse, error)
	// DeleteReplication deletes a replication.
	DeleteReplication(ctx context.Context, in *DeleteReplicationRequest, opts ...grpc.CallOption) (*DeleteReplicationResponse, error)
	// CreateReplicationExecution creates a new replication execution.
	CreateReplicationExecution(ctx context.Context, in *CreateReplicationExecutionRequest, opts ...grpc.CallOption) (*CreateReplicationExecutionResponse, error)
	// ListReplicationExecutions lists all replication executions.
	ListReplicationExecutions(ctx context.Context, in *ListReplicationExecutionsRequest, opts ...grpc.CallOption) (*ListReplicationExecutionsResponse, error)
	// StopReplicationExecution stops a replication execution.
	StopReplicationExecution(ctx context.Context, in *StopReplicationExecutionRequest, opts ...grpc.CallOption) (*StopReplicationExecutionResponse, error)
}

type replicationClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationClient(cc grpc.ClientConnInterface) ReplicationClient {
	return &replicationClient{cc}
}

func (c *replicationClient) ListReplications(ctx context.Context, in *ListReplicationsRequest, opts ...grpc.CallOption) (*ListReplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReplicationsResponse)
	err := c.cc.Invoke(ctx, Replication_ListReplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) CreateReplication(ctx context.Context, in *CreateReplicationRequest, opts ...grpc.CallOption) (*CreateReplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReplicationResponse)
	err := c.cc.Invoke(ctx, Replication_CreateReplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) UpdateReplication(ctx context.Context, in *UpdateReplicationRequest, opts ...grpc.CallOption) (*UpdateReplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReplicationResponse)
	err := c.cc.Invoke(ctx, Replication_UpdateReplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) DeleteReplication(ctx context.Context, in *DeleteReplicationRequest, opts ...grpc.CallOption) (*DeleteReplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteReplicationResponse)
	err := c.cc.Invoke(ctx, Replication_DeleteReplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) CreateReplicationExecution(ctx context.Context, in *CreateReplicationExecutionRequest, opts ...grpc.CallOption) (*CreateReplicationExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReplicationExecutionResponse)
	err := c.cc.Invoke(ctx, Replication_CreateReplicationExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) ListReplicationExecutions(ctx context.Context, in *ListReplicationExecutionsRequest, opts ...grpc.CallOption) (*ListReplicationExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReplicationExecutionsResponse)
	err := c.cc.Invoke(ctx, Replication_ListReplicationExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) StopReplicationExecution(ctx context.Context, in *StopReplicationExecutionRequest, opts ...grpc.CallOption) (*StopReplicationExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopReplicationExecutionResponse)
	err := c.cc.Invoke(ctx, Replication_StopReplicationExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServer is the server API for Replication service.
// All implementations should embed UnimplementedReplicationServer
// for forward compatibility.
type ReplicationServer interface {
	// ListReplications lists all replications.
	ListReplications(context.Context, *ListReplicationsRequest) (*ListReplicationsResponse, error)
	// CreateReplication creates a new replication.
	CreateReplication(context.Context, *CreateReplicationRequest) (*CreateReplicationResponse, error)
	// UpdateReplication updates a replication.
	UpdateReplication(context.Context, *UpdateReplicationRequest) (*UpdateReplicationResponse, error)
	// DeleteReplication deletes a replication.
	DeleteReplication(context.Context, *DeleteReplicationRequest) (*DeleteReplicationResponse, error)
	// CreateReplicationExecution creates a new replication execution.
	CreateReplicationExecution(context.Context, *CreateReplicationExecutionRequest) (*CreateReplicationExecutionResponse, error)
	// ListReplicationExecutions lists all replication executions.
	ListReplicationExecutions(context.Context, *ListReplicationExecutionsRequest) (*ListReplicationExecutionsResponse, error)
	// StopReplicationExecution stops a replication execution.
	StopReplicationExecution(context.Context, *StopReplicationExecutionRequest) (*StopReplicationExecutionResponse, error)
}

// UnimplementedReplicationServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicationServer struct{}

func (UnimplementedReplicationServer) ListReplications(context.Context, *ListReplicationsRequest) (*ListReplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReplications not implemented")
}
func (UnimplementedReplicationServer) CreateReplication(context.Context, *CreateReplicationRequest) (*CreateReplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReplication not implemented")
}
func (UnimplementedReplicationServer) UpdateReplication(context.Context, *UpdateReplicationRequest) (*UpdateReplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReplication not implemented")
}
func (UnimplementedReplicationServer) DeleteReplication(context.Context, *DeleteReplicationRequest) (*DeleteReplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteReplication not implemented")
}
func (UnimplementedReplicationServer) CreateReplicationExecution(context.Context, *CreateReplicationExecutionRequest) (*CreateReplicationExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReplicationExecution not implemented")
}
func (UnimplementedReplicationServer) ListReplicationExecutions(context.Context, *ListReplicationExecutionsRequest) (*ListReplicationExecutionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReplicationExecutions not implemented")
}
func (UnimplementedReplicationServer) StopReplicationExecution(context.Context, *StopReplicationExecutionRequest) (*StopReplicationExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopReplicationExecution not implemented")
}
func (UnimplementedReplicationServer) testEmbeddedByValue() {}

// UnsafeReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServer will
// result in compilation errors.
type UnsafeReplicationServer interface {
	mustEmbedUnimplementedReplicationServer()
}

func RegisterReplicationServer(s grpc.ServiceRegistrar, srv ReplicationServer) {
	// If the following call panics, it indicates UnimplementedReplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Replication_ServiceDesc, srv)
}

func _Replication_ListReplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).ListReplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_ListReplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).ListReplications(ctx, req.(*ListReplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_CreateReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).CreateReplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_CreateReplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).CreateReplication(ctx, req.(*CreateReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_UpdateReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).UpdateReplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_UpdateReplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).UpdateReplication(ctx, req.(*UpdateReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_DeleteReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).DeleteReplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_DeleteReplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).DeleteReplication(ctx, req.(*DeleteReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_CreateReplicationExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReplicationExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).CreateReplicationExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_CreateReplicationExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).CreateReplicationExecution(ctx, req.(*CreateReplicationExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_ListReplicationExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReplicationExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).ListReplicationExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_ListReplicationExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).ListReplicationExecutions(ctx, req.(*ListReplicationExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_StopReplicationExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopReplicationExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).StopReplicationExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replication_StopReplicationExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).StopReplicationExecution(ctx, req.(*StopReplicationExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Replication_ServiceDesc is the grpc.ServiceDesc for Replication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Replication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matrixhub.v1alpha1.Replication",
	HandlerType: (*ReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListReplications",
			Handler:    _Replication_ListReplications_Handler,
		},
		{
			MethodName: "CreateReplication",
			Handler:    _Replication_CreateReplication_Handler,
		},
		{
			MethodName: "UpdateReplication",
			Handler:    _Replication_UpdateReplication_Handler,
		},
		{
			MethodName: "DeleteReplication",
			Handler:    _Replication_DeleteReplication_Handler,
		},
		{
			MethodName: "CreateReplicationExecution",
			Handler:    _Replication_CreateReplicationExecution_Handler,
		},
		{
			MethodName: "ListReplicationExecutions",
			Handler:    _Replication_ListReplicationExecutions_Handler,
		},
		{
			MethodName: "StopReplicationExecution",
			Handler:    _Replication_StopReplicationExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha1/replication.proto",
}
