// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/replication.proto

package v1alpha1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicationPolicyType int32

const (
	ReplicationPolicyType_REPLICATION_POLICY_TYPE_UNSPECIFIED ReplicationPolicyType = 0
	ReplicationPolicyType_REPLICATION_POLICY_TYPE_PULL_BASE   ReplicationPolicyType = 1
	ReplicationPolicyType_REPLICATION_POLICY_TYPE_PUSH_BASE   ReplicationPolicyType = 2
)

// Enum value maps for ReplicationPolicyType.
var (
	ReplicationPolicyType_name = map[int32]string{
		0: "REPLICATION_POLICY_TYPE_UNSPECIFIED",
		1: "REPLICATION_POLICY_TYPE_PULL_BASE",
		2: "REPLICATION_POLICY_TYPE_PUSH_BASE",
	}
	ReplicationPolicyType_value = map[string]int32{
		"REPLICATION_POLICY_TYPE_UNSPECIFIED": 0,
		"REPLICATION_POLICY_TYPE_PULL_BASE":   1,
		"REPLICATION_POLICY_TYPE_PUSH_BASE":   2,
	}
)

func (x ReplicationPolicyType) Enum() *ReplicationPolicyType {
	p := new(ReplicationPolicyType)
	*p = x
	return p
}

func (x ReplicationPolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicationPolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_replication_proto_enumTypes[0].Descriptor()
}

func (ReplicationPolicyType) Type() protoreflect.EnumType {
	return &file_v1alpha1_replication_proto_enumTypes[0]
}

func (x ReplicationPolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicationPolicyType.Descriptor instead.
func (ReplicationPolicyType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{0}
}

type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNSPECIFIED ResourceType = 0
	ResourceType_RESOURCE_TYPE_MODEL       ResourceType = 1
	ResourceType_RESOURCE_TYPE_DATASET     ResourceType = 2
	ResourceType_RESOURCE_TYPE_ALL         ResourceType = 3
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "RESOURCE_TYPE_MODEL",
		2: "RESOURCE_TYPE_DATASET",
		3: "RESOURCE_TYPE_ALL",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED": 0,
		"RESOURCE_TYPE_MODEL":       1,
		"RESOURCE_TYPE_DATASET":     2,
		"RESOURCE_TYPE_ALL":         3,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_replication_proto_enumTypes[1].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_v1alpha1_replication_proto_enumTypes[1]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{1}
}

type TriggerType int32

const (
	TriggerType_TRIGGER_TYPE_UNSPECIFIED TriggerType = 0
	TriggerType_TRIGGER_TYPE_MANUAL      TriggerType = 1
	TriggerType_TRIGGER_TYPE_SCHEDULED   TriggerType = 2
)

// Enum value maps for TriggerType.
var (
	TriggerType_name = map[int32]string{
		0: "TRIGGER_TYPE_UNSPECIFIED",
		1: "TRIGGER_TYPE_MANUAL",
		2: "TRIGGER_TYPE_SCHEDULED",
	}
	TriggerType_value = map[string]int32{
		"TRIGGER_TYPE_UNSPECIFIED": 0,
		"TRIGGER_TYPE_MANUAL":      1,
		"TRIGGER_TYPE_SCHEDULED":   2,
	}
)

func (x TriggerType) Enum() *TriggerType {
	p := new(TriggerType)
	*p = x
	return p
}

func (x TriggerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_replication_proto_enumTypes[2].Descriptor()
}

func (TriggerType) Type() protoreflect.EnumType {
	return &file_v1alpha1_replication_proto_enumTypes[2]
}

func (x TriggerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerType.Descriptor instead.
func (TriggerType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{2}
}

type ReplicationExecutionStatus int32

const (
	ReplicationExecutionStatus_REPLICATION_EXECUTION_STATUS_UNSPECIFIED ReplicationExecutionStatus = 0
	ReplicationExecutionStatus_REPLICATION_EXECUTION_STATUS_RUNNING     ReplicationExecutionStatus = 1
	ReplicationExecutionStatus_REPLICATION_EXECUTION_STATUS_SUCCEEDED   ReplicationExecutionStatus = 2
	ReplicationExecutionStatus_REPLICATION_EXECUTION_STATUS_FAILED      ReplicationExecutionStatus = 3
	ReplicationExecutionStatus_REPLICATION_EXECUTION_STATUS_STOPPED     ReplicationExecutionStatus = 4
)

// Enum value maps for ReplicationExecutionStatus.
var (
	ReplicationExecutionStatus_name = map[int32]string{
		0: "REPLICATION_EXECUTION_STATUS_UNSPECIFIED",
		1: "REPLICATION_EXECUTION_STATUS_RUNNING",
		2: "REPLICATION_EXECUTION_STATUS_SUCCEEDED",
		3: "REPLICATION_EXECUTION_STATUS_FAILED",
		4: "REPLICATION_EXECUTION_STATUS_STOPPED",
	}
	ReplicationExecutionStatus_value = map[string]int32{
		"REPLICATION_EXECUTION_STATUS_UNSPECIFIED": 0,
		"REPLICATION_EXECUTION_STATUS_RUNNING":     1,
		"REPLICATION_EXECUTION_STATUS_SUCCEEDED":   2,
		"REPLICATION_EXECUTION_STATUS_FAILED":      3,
		"REPLICATION_EXECUTION_STATUS_STOPPED":     4,
	}
)

func (x ReplicationExecutionStatus) Enum() *ReplicationExecutionStatus {
	p := new(ReplicationExecutionStatus)
	*p = x
	return p
}

func (x ReplicationExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicationExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_replication_proto_enumTypes[3].Descriptor()
}

func (ReplicationExecutionStatus) Type() protoreflect.EnumType {
	return &file_v1alpha1_replication_proto_enumTypes[3]
}

func (x ReplicationExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicationExecutionStatus.Descriptor instead.
func (ReplicationExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{3}
}

type PullBasePolicy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SourceRegistryId   string                 `protobuf:"bytes,1,opt,name=source_registry_id,json=sourceRegistryId,proto3" json:"source_registry_id,omitempty"`
	ResourceName       string                 `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceType       ResourceType           `protobuf:"varint,3,opt,name=resource_type,json=resourceType,proto3,enum=matrixhub.v1alpha1.ResourceType" json:"resource_type,omitempty"`
	TargetResourceName string                 `protobuf:"bytes,4,opt,name=target_resource_name,json=targetResourceName,proto3" json:"target_resource_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PullBasePolicy) Reset() {
	*x = PullBasePolicy{}
	mi := &file_v1alpha1_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullBasePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullBasePolicy) ProtoMessage() {}

func (x *PullBasePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullBasePolicy.ProtoReflect.Descriptor instead.
func (*PullBasePolicy) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{0}
}

func (x *PullBasePolicy) GetSourceRegistryId() string {
	if x != nil {
		return x.SourceRegistryId
	}
	return ""
}

func (x *PullBasePolicy) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *PullBasePolicy) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *PullBasePolicy) GetTargetResourceName() string {
	if x != nil {
		return x.TargetResourceName
	}
	return ""
}

type PushBasePolicy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResourceName       string                 `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceType       ResourceType           `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=matrixhub.v1alpha1.ResourceType" json:"resource_type,omitempty"`
	TargetRegistryId   string                 `protobuf:"bytes,3,opt,name=target_registry_id,json=targetRegistryId,proto3" json:"target_registry_id,omitempty"`
	TargetResourceName string                 `protobuf:"bytes,4,opt,name=target_resource_name,json=targetResourceName,proto3" json:"target_resource_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PushBasePolicy) Reset() {
	*x = PushBasePolicy{}
	mi := &file_v1alpha1_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBasePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBasePolicy) ProtoMessage() {}

func (x *PushBasePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBasePolicy.ProtoReflect.Descriptor instead.
func (*PushBasePolicy) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{1}
}

func (x *PushBasePolicy) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *PushBasePolicy) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *PushBasePolicy) GetTargetRegistryId() string {
	if x != nil {
		return x.TargetRegistryId
	}
	return ""
}

func (x *PushBasePolicy) GetTargetResourceName() string {
	if x != nil {
		return x.TargetResourceName
	}
	return ""
}

type ReplicationItem struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PolicyType  ReplicationPolicyType  `protobuf:"varint,4,opt,name=policy_type,json=policyType,proto3,enum=matrixhub.v1alpha1.ReplicationPolicyType" json:"policy_type,omitempty"`
	TriggerType TriggerType            `protobuf:"varint,5,opt,name=trigger_type,json=triggerType,proto3,enum=matrixhub.v1alpha1.TriggerType" json:"trigger_type,omitempty"`
	// Types that are valid to be assigned to Policy:
	//
	//	*ReplicationItem_PullBasePolicy
	//	*ReplicationItem_PushBasePolicy
	Policy isReplicationItem_Policy `protobuf_oneof:"policy"`
	// The bandwidth to use for the replication.
	Bandwidth     string `protobuf:"bytes,8,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	IsOverwrite   bool   `protobuf:"varint,9,opt,name=is_overwrite,json=isOverwrite,proto3" json:"is_overwrite,omitempty"`
	IsDisabled    bool   `protobuf:"varint,10,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationItem) Reset() {
	*x = ReplicationItem{}
	mi := &file_v1alpha1_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationItem) ProtoMessage() {}

func (x *ReplicationItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationItem.ProtoReflect.Descriptor instead.
func (*ReplicationItem) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicationItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReplicationItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReplicationItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReplicationItem) GetPolicyType() ReplicationPolicyType {
	if x != nil {
		return x.PolicyType
	}
	return ReplicationPolicyType_REPLICATION_POLICY_TYPE_UNSPECIFIED
}

func (x *ReplicationItem) GetTriggerType() TriggerType {
	if x != nil {
		return x.TriggerType
	}
	return TriggerType_TRIGGER_TYPE_UNSPECIFIED
}

func (x *ReplicationItem) GetPolicy() isReplicationItem_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *ReplicationItem) GetPullBasePolicy() *PullBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*ReplicationItem_PullBasePolicy); ok {
			return x.PullBasePolicy
		}
	}
	return nil
}

func (x *ReplicationItem) GetPushBasePolicy() *PushBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*ReplicationItem_PushBasePolicy); ok {
			return x.PushBasePolicy
		}
	}
	return nil
}

func (x *ReplicationItem) GetBandwidth() string {
	if x != nil {
		return x.Bandwidth
	}
	return ""
}

func (x *ReplicationItem) GetIsOverwrite() bool {
	if x != nil {
		return x.IsOverwrite
	}
	return false
}

func (x *ReplicationItem) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

type isReplicationItem_Policy interface {
	isReplicationItem_Policy()
}

type ReplicationItem_PullBasePolicy struct {
	PullBasePolicy *PullBasePolicy `protobuf:"bytes,6,opt,name=pull_base_policy,json=pullBasePolicy,proto3,oneof"`
}

type ReplicationItem_PushBasePolicy struct {
	PushBasePolicy *PushBasePolicy `protobuf:"bytes,7,opt,name=push_base_policy,json=pushBasePolicy,proto3,oneof"`
}

func (*ReplicationItem_PullBasePolicy) isReplicationItem_Policy() {}

func (*ReplicationItem_PushBasePolicy) isReplicationItem_Policy() {}

type CreateReplicationRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PolicyType  ReplicationPolicyType  `protobuf:"varint,3,opt,name=policy_type,json=policyType,proto3,enum=matrixhub.v1alpha1.ReplicationPolicyType" json:"policy_type,omitempty"`
	TriggerType TriggerType            `protobuf:"varint,4,opt,name=trigger_type,json=triggerType,proto3,enum=matrixhub.v1alpha1.TriggerType" json:"trigger_type,omitempty"`
	// The policy to use for the replication.
	// only one of pull_base_policy or push_base_policy should be set.
	//
	// Types that are valid to be assigned to Policy:
	//
	//	*CreateReplicationRequest_PullBasePolicy
	//	*CreateReplicationRequest_PushBasePolicy
	Policy isCreateReplicationRequest_Policy `protobuf_oneof:"policy"`
	// The bandwidth to use for the replication.
	Bandwidth     string `protobuf:"bytes,7,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	IsOverwrite   bool   `protobuf:"varint,8,opt,name=is_overwrite,json=isOverwrite,proto3" json:"is_overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplicationRequest) Reset() {
	*x = CreateReplicationRequest{}
	mi := &file_v1alpha1_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplicationRequest) ProtoMessage() {}

func (x *CreateReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateReplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateReplicationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateReplicationRequest) GetPolicyType() ReplicationPolicyType {
	if x != nil {
		return x.PolicyType
	}
	return ReplicationPolicyType_REPLICATION_POLICY_TYPE_UNSPECIFIED
}

func (x *CreateReplicationRequest) GetTriggerType() TriggerType {
	if x != nil {
		return x.TriggerType
	}
	return TriggerType_TRIGGER_TYPE_UNSPECIFIED
}

func (x *CreateReplicationRequest) GetPolicy() isCreateReplicationRequest_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *CreateReplicationRequest) GetPullBasePolicy() *PullBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*CreateReplicationRequest_PullBasePolicy); ok {
			return x.PullBasePolicy
		}
	}
	return nil
}

func (x *CreateReplicationRequest) GetPushBasePolicy() *PushBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*CreateReplicationRequest_PushBasePolicy); ok {
			return x.PushBasePolicy
		}
	}
	return nil
}

func (x *CreateReplicationRequest) GetBandwidth() string {
	if x != nil {
		return x.Bandwidth
	}
	return ""
}

func (x *CreateReplicationRequest) GetIsOverwrite() bool {
	if x != nil {
		return x.IsOverwrite
	}
	return false
}

type isCreateReplicationRequest_Policy interface {
	isCreateReplicationRequest_Policy()
}

type CreateReplicationRequest_PullBasePolicy struct {
	PullBasePolicy *PullBasePolicy `protobuf:"bytes,5,opt,name=pull_base_policy,json=pullBasePolicy,proto3,oneof"`
}

type CreateReplicationRequest_PushBasePolicy struct {
	PushBasePolicy *PushBasePolicy `protobuf:"bytes,6,opt,name=push_base_policy,json=pushBasePolicy,proto3,oneof"`
}

func (*CreateReplicationRequest_PullBasePolicy) isCreateReplicationRequest_Policy() {}

func (*CreateReplicationRequest_PushBasePolicy) isCreateReplicationRequest_Policy() {}

type CreateReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replication   *ReplicationItem       `protobuf:"bytes,1,opt,name=replication,proto3" json:"replication,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplicationResponse) Reset() {
	*x = CreateReplicationResponse{}
	mi := &file_v1alpha1_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplicationResponse) ProtoMessage() {}

func (x *CreateReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateReplicationResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReplicationResponse) GetReplication() *ReplicationItem {
	if x != nil {
		return x.Replication
	}
	return nil
}

type UpdateReplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicationId int32                  `protobuf:"varint,1,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TriggerType   TriggerType            `protobuf:"varint,4,opt,name=trigger_type,json=triggerType,proto3,enum=matrixhub.v1alpha1.TriggerType" json:"trigger_type,omitempty"`
	// The policy to use for the replication.
	// only one of pull_base_policy or push_base_policy should be set.
	//
	// Types that are valid to be assigned to Policy:
	//
	//	*UpdateReplicationRequest_PullBasePolicy
	//	*UpdateReplicationRequest_PushBasePolicy
	Policy isUpdateReplicationRequest_Policy `protobuf_oneof:"policy"`
	// The bandwidth to use for the replication.
	Bandwidth     string `protobuf:"bytes,7,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	IsOverwrite   bool   `protobuf:"varint,8,opt,name=is_overwrite,json=isOverwrite,proto3" json:"is_overwrite,omitempty"`
	IsDisabled    bool   `protobuf:"varint,9,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReplicationRequest) Reset() {
	*x = UpdateReplicationRequest{}
	mi := &file_v1alpha1_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplicationRequest) ProtoMessage() {}

func (x *UpdateReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateReplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateReplicationRequest) GetReplicationId() int32 {
	if x != nil {
		return x.ReplicationId
	}
	return 0
}

func (x *UpdateReplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateReplicationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateReplicationRequest) GetTriggerType() TriggerType {
	if x != nil {
		return x.TriggerType
	}
	return TriggerType_TRIGGER_TYPE_UNSPECIFIED
}

func (x *UpdateReplicationRequest) GetPolicy() isUpdateReplicationRequest_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *UpdateReplicationRequest) GetPullBasePolicy() *PullBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*UpdateReplicationRequest_PullBasePolicy); ok {
			return x.PullBasePolicy
		}
	}
	return nil
}

func (x *UpdateReplicationRequest) GetPushBasePolicy() *PushBasePolicy {
	if x != nil {
		if x, ok := x.Policy.(*UpdateReplicationRequest_PushBasePolicy); ok {
			return x.PushBasePolicy
		}
	}
	return nil
}

func (x *UpdateReplicationRequest) GetBandwidth() string {
	if x != nil {
		return x.Bandwidth
	}
	return ""
}

func (x *UpdateReplicationRequest) GetIsOverwrite() bool {
	if x != nil {
		return x.IsOverwrite
	}
	return false
}

func (x *UpdateReplicationRequest) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

type isUpdateReplicationRequest_Policy interface {
	isUpdateReplicationRequest_Policy()
}

type UpdateReplicationRequest_PullBasePolicy struct {
	PullBasePolicy *PullBasePolicy `protobuf:"bytes,5,opt,name=pull_base_policy,json=pullBasePolicy,proto3,oneof"`
}

type UpdateReplicationRequest_PushBasePolicy struct {
	PushBasePolicy *PushBasePolicy `protobuf:"bytes,6,opt,name=push_base_policy,json=pushBasePolicy,proto3,oneof"`
}

func (*UpdateReplicationRequest_PullBasePolicy) isUpdateReplicationRequest_Policy() {}

func (*UpdateReplicationRequest_PushBasePolicy) isUpdateReplicationRequest_Policy() {}

type UpdateReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replication   *ReplicationItem       `protobuf:"bytes,1,opt,name=replication,proto3" json:"replication,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReplicationResponse) Reset() {
	*x = UpdateReplicationResponse{}
	mi := &file_v1alpha1_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplicationResponse) ProtoMessage() {}

func (x *UpdateReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplicationResponse.ProtoReflect.Descriptor instead.
func (*UpdateReplicationResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateReplicationResponse) GetReplication() *ReplicationItem {
	if x != nil {
		return x.Replication
	}
	return nil
}

type DeleteReplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicationId int32                  `protobuf:"varint,1,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplicationRequest) Reset() {
	*x = DeleteReplicationRequest{}
	mi := &file_v1alpha1_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplicationRequest) ProtoMessage() {}

func (x *DeleteReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReplicationRequest) GetReplicationId() int32 {
	if x != nil {
		return x.ReplicationId
	}
	return 0
}

type DeleteReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replication   *ReplicationItem       `protobuf:"bytes,1,opt,name=replication,proto3" json:"replication,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplicationResponse) Reset() {
	*x = DeleteReplicationResponse{}
	mi := &file_v1alpha1_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplicationResponse) ProtoMessage() {}

func (x *DeleteReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplicationResponse.ProtoReflect.Descriptor instead.
func (*DeleteReplicationResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteReplicationResponse) GetReplication() *ReplicationItem {
	if x != nil {
		return x.Replication
	}
	return nil
}

type ListReplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicationsRequest) Reset() {
	*x = ListReplicationsRequest{}
	mi := &file_v1alpha1_replication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicationsRequest) ProtoMessage() {}

func (x *ListReplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListReplicationsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{9}
}

func (x *ListReplicationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReplicationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListReplicationsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListReplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replications  []*ReplicationItem     `protobuf:"bytes,1,rep,name=replications,proto3" json:"replications,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicationsResponse) Reset() {
	*x = ListReplicationsResponse{}
	mi := &file_v1alpha1_replication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicationsResponse) ProtoMessage() {}

func (x *ListReplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListReplicationsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{10}
}

func (x *ListReplicationsResponse) GetReplications() []*ReplicationItem {
	if x != nil {
		return x.Replications
	}
	return nil
}

func (x *ListReplicationsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CreateReplicationExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicationId int32                  `protobuf:"varint,1,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplicationExecutionRequest) Reset() {
	*x = CreateReplicationExecutionRequest{}
	mi := &file_v1alpha1_replication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplicationExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplicationExecutionRequest) ProtoMessage() {}

func (x *CreateReplicationExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplicationExecutionRequest.ProtoReflect.Descriptor instead.
func (*CreateReplicationExecutionRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{11}
}

func (x *CreateReplicationExecutionRequest) GetReplicationId() int32 {
	if x != nil {
		return x.ReplicationId
	}
	return 0
}

type CreateReplicationExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplicationExecutionResponse) Reset() {
	*x = CreateReplicationExecutionResponse{}
	mi := &file_v1alpha1_replication_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplicationExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplicationExecutionResponse) ProtoMessage() {}

func (x *CreateReplicationExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplicationExecutionResponse.ProtoReflect.Descriptor instead.
func (*CreateReplicationExecutionResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{12}
}

func (x *CreateReplicationExecutionResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReplicationExecution struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Id                 int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReplicationId      int32                      `protobuf:"varint,2,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	TriggerType        TriggerType                `protobuf:"varint,3,opt,name=trigger_type,json=triggerType,proto3,enum=matrixhub.v1alpha1.TriggerType" json:"trigger_type,omitempty"`
	Status             ReplicationExecutionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=matrixhub.v1alpha1.ReplicationExecutionStatus" json:"status,omitempty"`
	StartedTimestamp   int64                      `protobuf:"varint,5,opt,name=started_timestamp,json=startedTimestamp,proto3" json:"started_timestamp,omitempty"`
	CompletedTimestamp int64                      `protobuf:"varint,6,opt,name=completed_timestamp,json=completedTimestamp,proto3" json:"completed_timestamp,omitempty"`
	TotalItems         int64                      `protobuf:"varint,7,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	SuccessfulItems    int64                      `protobuf:"varint,8,opt,name=successful_items,json=successfulItems,proto3" json:"successful_items,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReplicationExecution) Reset() {
	*x = ReplicationExecution{}
	mi := &file_v1alpha1_replication_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationExecution) ProtoMessage() {}

func (x *ReplicationExecution) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationExecution.ProtoReflect.Descriptor instead.
func (*ReplicationExecution) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{13}
}

func (x *ReplicationExecution) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReplicationExecution) GetReplicationId() int32 {
	if x != nil {
		return x.ReplicationId
	}
	return 0
}

func (x *ReplicationExecution) GetTriggerType() TriggerType {
	if x != nil {
		return x.TriggerType
	}
	return TriggerType_TRIGGER_TYPE_UNSPECIFIED
}

func (x *ReplicationExecution) GetStatus() ReplicationExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ReplicationExecutionStatus_REPLICATION_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ReplicationExecution) GetStartedTimestamp() int64 {
	if x != nil {
		return x.StartedTimestamp
	}
	return 0
}

func (x *ReplicationExecution) GetCompletedTimestamp() int64 {
	if x != nil {
		return x.CompletedTimestamp
	}
	return 0
}

func (x *ReplicationExecution) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *ReplicationExecution) GetSuccessfulItems() int64 {
	if x != nil {
		return x.SuccessfulItems
	}
	return 0
}

type ListReplicationExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicationId int32                  `protobuf:"varint,1,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicationExecutionsRequest) Reset() {
	*x = ListReplicationExecutionsRequest{}
	mi := &file_v1alpha1_replication_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicationExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicationExecutionsRequest) ProtoMessage() {}

func (x *ListReplicationExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicationExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListReplicationExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{14}
}

func (x *ListReplicationExecutionsRequest) GetReplicationId() int32 {
	if x != nil {
		return x.ReplicationId
	}
	return 0
}

func (x *ListReplicationExecutionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReplicationExecutionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListReplicationExecutionsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListReplicationExecutionsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Executions    []*ReplicationExecution `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	Pagination    *Pagination             `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicationExecutionsResponse) Reset() {
	*x = ListReplicationExecutionsResponse{}
	mi := &file_v1alpha1_replication_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicationExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicationExecutionsResponse) ProtoMessage() {}

func (x *ListReplicationExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicationExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListReplicationExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{15}
}

func (x *ListReplicationExecutionsResponse) GetExecutions() []*ReplicationExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *ListReplicationExecutionsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type StopReplicationExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicationId int32                  `protobuf:"varint,1,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	ExecutionId   int32                  `protobuf:"varint,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopReplicationExecutionRequest) Reset() {
	*x = StopReplicationExecutionRequest{}
	mi := &file_v1alpha1_replication_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopReplicationExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopReplicationExecutionRequest) ProtoMessage() {}

func (x *StopReplicationExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopReplicationExecutionRequest.ProtoReflect.Descriptor instead.
func (*StopReplicationExecutionRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{16}
}

func (x *StopReplicationExecutionRequest) GetReplicationId() int32 {
	if x != nil {
		return x.ReplicationId
	}
	return 0
}

func (x *StopReplicationExecutionRequest) GetExecutionId() int32 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

type StopReplicationExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *ReplicationExecution  `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopReplicationExecutionResponse) Reset() {
	*x = StopReplicationExecutionResponse{}
	mi := &file_v1alpha1_replication_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopReplicationExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopReplicationExecutionResponse) ProtoMessage() {}

func (x *StopReplicationExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_replication_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopReplicationExecutionResponse.ProtoReflect.Descriptor instead.
func (*StopReplicationExecutionResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_replication_proto_rawDescGZIP(), []int{17}
}

func (x *StopReplicationExecutionResponse) GetExecution() *ReplicationExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

var File_v1alpha1_replication_proto protoreflect.FileDescriptor

const file_v1alpha1_replication_proto_rawDesc = "" +
	"\n" +
	"\x1av1alpha1/replication.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x14v1alpha1/utils.proto\"\xdc\x01\n" +
	"\x0ePullBasePolicy\x12,\n" +
	"\x12source_registry_id\x18\x01 \x01(\tR\x10sourceRegistryId\x12#\n" +
	"\rresource_name\x18\x02 \x01(\tR\fresourceName\x12E\n" +
	"\rresource_type\x18\x03 \x01(\x0e2 .matrixhub.v1alpha1.ResourceTypeR\fresourceType\x120\n" +
	"\x14target_resource_name\x18\x04 \x01(\tR\x12targetResourceName\"\xdc\x01\n" +
	"\x0ePushBasePolicy\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12E\n" +
	"\rresource_type\x18\x02 \x01(\x0e2 .matrixhub.v1alpha1.ResourceTypeR\fresourceType\x12,\n" +
	"\x12target_registry_id\x18\x03 \x01(\tR\x10targetRegistryId\x120\n" +
	"\x14target_resource_name\x18\x04 \x01(\tR\x12targetResourceName\"\xf3\x03\n" +
	"\x0fReplicationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12J\n" +
	"\vpolicy_type\x18\x04 \x01(\x0e2).matrixhub.v1alpha1.ReplicationPolicyTypeR\n" +
	"policyType\x12B\n" +
	"\ftrigger_type\x18\x05 \x01(\x0e2\x1f.matrixhub.v1alpha1.triggerTypeR\vtriggerType\x12N\n" +
	"\x10pull_base_policy\x18\x06 \x01(\v2\".matrixhub.v1alpha1.PullBasePolicyH\x00R\x0epullBasePolicy\x12N\n" +
	"\x10push_base_policy\x18\a \x01(\v2\".matrixhub.v1alpha1.PushBasePolicyH\x00R\x0epushBasePolicy\x12\x1c\n" +
	"\tbandwidth\x18\b \x01(\tR\tbandwidth\x12!\n" +
	"\fis_overwrite\x18\t \x01(\bR\visOverwrite\x12\x1f\n" +
	"\vis_disabled\x18\n" +
	" \x01(\bR\n" +
	"isDisabledB\b\n" +
	"\x06policy\"\xcb\x03\n" +
	"\x18CreateReplicationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12J\n" +
	"\vpolicy_type\x18\x03 \x01(\x0e2).matrixhub.v1alpha1.ReplicationPolicyTypeR\n" +
	"policyType\x12B\n" +
	"\ftrigger_type\x18\x04 \x01(\x0e2\x1f.matrixhub.v1alpha1.triggerTypeR\vtriggerType\x12N\n" +
	"\x10pull_base_policy\x18\x05 \x01(\v2\".matrixhub.v1alpha1.PullBasePolicyH\x00R\x0epullBasePolicy\x12N\n" +
	"\x10push_base_policy\x18\x06 \x01(\v2\".matrixhub.v1alpha1.PushBasePolicyH\x00R\x0epushBasePolicy\x12\x1c\n" +
	"\tbandwidth\x18\a \x01(\tR\tbandwidth\x12!\n" +
	"\fis_overwrite\x18\b \x01(\bR\visOverwriteB\b\n" +
	"\x06policy\"b\n" +
	"\x19CreateReplicationResponse\x12E\n" +
	"\vreplication\x18\x01 \x01(\v2#.matrixhub.v1alpha1.ReplicationItemR\vreplication\"\xc7\x03\n" +
	"\x18UpdateReplicationRequest\x12%\n" +
	"\x0ereplication_id\x18\x01 \x01(\x05R\rreplicationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12B\n" +
	"\ftrigger_type\x18\x04 \x01(\x0e2\x1f.matrixhub.v1alpha1.triggerTypeR\vtriggerType\x12N\n" +
	"\x10pull_base_policy\x18\x05 \x01(\v2\".matrixhub.v1alpha1.PullBasePolicyH\x00R\x0epullBasePolicy\x12N\n" +
	"\x10push_base_policy\x18\x06 \x01(\v2\".matrixhub.v1alpha1.PushBasePolicyH\x00R\x0epushBasePolicy\x12\x1c\n" +
	"\tbandwidth\x18\a \x01(\tR\tbandwidth\x12!\n" +
	"\fis_overwrite\x18\b \x01(\bR\visOverwrite\x12\x1f\n" +
	"\vis_disabled\x18\t \x01(\bR\n" +
	"isDisabledB\b\n" +
	"\x06policy\"b\n" +
	"\x19UpdateReplicationResponse\x12E\n" +
	"\vreplication\x18\x01 \x01(\v2#.matrixhub.v1alpha1.ReplicationItemR\vreplication\"A\n" +
	"\x18DeleteReplicationRequest\x12%\n" +
	"\x0ereplication_id\x18\x01 \x01(\x05R\rreplicationId\"b\n" +
	"\x19DeleteReplicationResponse\x12E\n" +
	"\vreplication\x18\x01 \x01(\v2#.matrixhub.v1alpha1.ReplicationItemR\vreplication\"b\n" +
	"\x17ListReplicationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\xa3\x01\n" +
	"\x18ListReplicationsResponse\x12G\n" +
	"\freplications\x18\x01 \x03(\v2#.matrixhub.v1alpha1.ReplicationItemR\freplications\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.matrixhub.v1alpha1.PaginationR\n" +
	"pagination\"J\n" +
	"!CreateReplicationExecutionRequest\x12%\n" +
	"\x0ereplication_id\x18\x01 \x01(\x05R\rreplicationId\"4\n" +
	"\"CreateReplicationExecutionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x83\x03\n" +
	"\x14ReplicationExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12%\n" +
	"\x0ereplication_id\x18\x02 \x01(\x05R\rreplicationId\x12B\n" +
	"\ftrigger_type\x18\x03 \x01(\x0e2\x1f.matrixhub.v1alpha1.triggerTypeR\vtriggerType\x12F\n" +
	"\x06status\x18\x04 \x01(\x0e2..matrixhub.v1alpha1.ReplicationExecutionStatusR\x06status\x12+\n" +
	"\x11started_timestamp\x18\x05 \x01(\x03R\x10startedTimestamp\x12/\n" +
	"\x13completed_timestamp\x18\x06 \x01(\x03R\x12completedTimestamp\x12\x1f\n" +
	"\vtotal_items\x18\a \x01(\x03R\n" +
	"totalItems\x12)\n" +
	"\x10successful_items\x18\b \x01(\x03R\x0fsuccessfulItems\"\x92\x01\n" +
	" ListReplicationExecutionsRequest\x12%\n" +
	"\x0ereplication_id\x18\x01 \x01(\x05R\rreplicationId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"\xad\x01\n" +
	"!ListReplicationExecutionsResponse\x12H\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2(.matrixhub.v1alpha1.ReplicationExecutionR\n" +
	"executions\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.matrixhub.v1alpha1.PaginationR\n" +
	"pagination\"k\n" +
	"\x1fStopReplicationExecutionRequest\x12%\n" +
	"\x0ereplication_id\x18\x01 \x01(\x05R\rreplicationId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\x05R\vexecutionId\"j\n" +
	" StopReplicationExecutionResponse\x12F\n" +
	"\texecution\x18\x01 \x01(\v2(.matrixhub.v1alpha1.ReplicationExecutionR\texecution*\x8e\x01\n" +
	"\x15ReplicationPolicyType\x12'\n" +
	"#REPLICATION_POLICY_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!REPLICATION_POLICY_TYPE_PULL_BASE\x10\x01\x12%\n" +
	"!REPLICATION_POLICY_TYPE_PUSH_BASE\x10\x02*x\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RESOURCE_TYPE_MODEL\x10\x01\x12\x19\n" +
	"\x15RESOURCE_TYPE_DATASET\x10\x02\x12\x15\n" +
	"\x11RESOURCE_TYPE_ALL\x10\x03*`\n" +
	"\vtriggerType\x12\x1c\n" +
	"\x18TRIGGER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TRIGGER_TYPE_MANUAL\x10\x01\x12\x1a\n" +
	"\x16TRIGGER_TYPE_SCHEDULED\x10\x02*\xf3\x01\n" +
	"\x1aReplicationExecutionStatus\x12,\n" +
	"(REPLICATION_EXECUTION_STATUS_UNSPECIFIED\x10\x00\x12(\n" +
	"$REPLICATION_EXECUTION_STATUS_RUNNING\x10\x01\x12*\n" +
	"&REPLICATION_EXECUTION_STATUS_SUCCEEDED\x10\x02\x12'\n" +
	"#REPLICATION_EXECUTION_STATUS_FAILED\x10\x03\x12(\n" +
	"$REPLICATION_EXECUTION_STATUS_STOPPED\x10\x042\x83\n" +
	"\n" +
	"\vReplication\x12\x91\x01\n" +
	"\x10ListReplications\x12+.matrixhub.v1alpha1.ListReplicationsRequest\x1a,.matrixhub.v1alpha1.ListReplicationsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1alpha1/replications\x12\x97\x01\n" +
	"\x11CreateReplication\x12,.matrixhub.v1alpha1.CreateReplicationRequest\x1a-.matrixhub.v1alpha1.CreateReplicationResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1alpha1/replications\x12\xa8\x01\n" +
	"\x11UpdateReplication\x12,.matrixhub.v1alpha1.UpdateReplicationRequest\x1a-.matrixhub.v1alpha1.UpdateReplicationResponse\"6\x82\xd3\xe4\x93\x020:\x01*\x1a+/api/v1alpha1/replications/{replication_id}\x12\xa5\x01\n" +
	"\x11DeleteReplication\x12,.matrixhub.v1alpha1.DeleteReplicationRequest\x1a-.matrixhub.v1alpha1.DeleteReplicationResponse\"3\x82\xd3\xe4\x93\x02-*+/api/v1alpha1/replications/{replication_id}\x12\xcb\x01\n" +
	"\x1aCreateReplicationExecution\x125.matrixhub.v1alpha1.CreateReplicationExecutionRequest\x1a6.matrixhub.v1alpha1.CreateReplicationExecutionResponse\">\x82\xd3\xe4\x93\x028\"6/api/v1alpha1/replications/{replication_id}/executions\x12\xc8\x01\n" +
	"\x19ListReplicationExecutions\x124.matrixhub.v1alpha1.ListReplicationExecutionsRequest\x1a5.matrixhub.v1alpha1.ListReplicationExecutionsResponse\">\x82\xd3\xe4\x93\x028\x126/api/v1alpha1/replications/{replication_id}/executions\x12\xd9\x01\n" +
	"\x18StopReplicationExecution\x123.matrixhub.v1alpha1.StopReplicationExecutionRequest\x1a4.matrixhub.v1alpha1.StopReplicationExecutionResponse\"R\x82\xd3\xe4\x93\x02L\"J/api/v1alpha1/replications/{replication_id}/executions/{execution_id}/stopB<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_replication_proto_rawDescOnce sync.Once
	file_v1alpha1_replication_proto_rawDescData []byte
)

func file_v1alpha1_replication_proto_rawDescGZIP() []byte {
	file_v1alpha1_replication_proto_rawDescOnce.Do(func() {
		file_v1alpha1_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_replication_proto_rawDesc), len(file_v1alpha1_replication_proto_rawDesc)))
	})
	return file_v1alpha1_replication_proto_rawDescData
}

var file_v1alpha1_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_v1alpha1_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_v1alpha1_replication_proto_goTypes = []any{
	(ReplicationPolicyType)(0),                 // 0: matrixhub.v1alpha1.ReplicationPolicyType
	(ResourceType)(0),                          // 1: matrixhub.v1alpha1.ResourceType
	(TriggerType)(0),                           // 2: matrixhub.v1alpha1.triggerType
	(ReplicationExecutionStatus)(0),            // 3: matrixhub.v1alpha1.ReplicationExecutionStatus
	(*PullBasePolicy)(nil),                     // 4: matrixhub.v1alpha1.PullBasePolicy
	(*PushBasePolicy)(nil),                     // 5: matrixhub.v1alpha1.PushBasePolicy
	(*ReplicationItem)(nil),                    // 6: matrixhub.v1alpha1.ReplicationItem
	(*CreateReplicationRequest)(nil),           // 7: matrixhub.v1alpha1.CreateReplicationRequest
	(*CreateReplicationResponse)(nil),          // 8: matrixhub.v1alpha1.CreateReplicationResponse
	(*UpdateReplicationRequest)(nil),           // 9: matrixhub.v1alpha1.UpdateReplicationRequest
	(*UpdateReplicationResponse)(nil),          // 10: matrixhub.v1alpha1.UpdateReplicationResponse
	(*DeleteReplicationRequest)(nil),           // 11: matrixhub.v1alpha1.DeleteReplicationRequest
	(*DeleteReplicationResponse)(nil),          // 12: matrixhub.v1alpha1.DeleteReplicationResponse
	(*ListReplicationsRequest)(nil),            // 13: matrixhub.v1alpha1.ListReplicationsRequest
	(*ListReplicationsResponse)(nil),           // 14: matrixhub.v1alpha1.ListReplicationsResponse
	(*CreateReplicationExecutionRequest)(nil),  // 15: matrixhub.v1alpha1.CreateReplicationExecutionRequest
	(*CreateReplicationExecutionResponse)(nil), // 16: matrixhub.v1alpha1.CreateReplicationExecutionResponse
	(*ReplicationExecution)(nil),               // 17: matrixhub.v1alpha1.ReplicationExecution
	(*ListReplicationExecutionsRequest)(nil),   // 18: matrixhub.v1alpha1.ListReplicationExecutionsRequest
	(*ListReplicationExecutionsResponse)(nil),  // 19: matrixhub.v1alpha1.ListReplicationExecutionsResponse
	(*StopReplicationExecutionRequest)(nil),    // 20: matrixhub.v1alpha1.StopReplicationExecutionRequest
	(*StopReplicationExecutionResponse)(nil),   // 21: matrixhub.v1alpha1.StopReplicationExecutionResponse
	(*Pagination)(nil),                         // 22: matrixhub.v1alpha1.Pagination
}
var file_v1alpha1_replication_proto_depIdxs = []int32{
	1,  // 0: matrixhub.v1alpha1.PullBasePolicy.resource_type:type_name -> matrixhub.v1alpha1.ResourceType
	1,  // 1: matrixhub.v1alpha1.PushBasePolicy.resource_type:type_name -> matrixhub.v1alpha1.ResourceType
	0,  // 2: matrixhub.v1alpha1.ReplicationItem.policy_type:type_name -> matrixhub.v1alpha1.ReplicationPolicyType
	2,  // 3: matrixhub.v1alpha1.ReplicationItem.trigger_type:type_name -> matrixhub.v1alpha1.triggerType
	4,  // 4: matrixhub.v1alpha1.ReplicationItem.pull_base_policy:type_name -> matrixhub.v1alpha1.PullBasePolicy
	5,  // 5: matrixhub.v1alpha1.ReplicationItem.push_base_policy:type_name -> matrixhub.v1alpha1.PushBasePolicy
	0,  // 6: matrixhub.v1alpha1.CreateReplicationRequest.policy_type:type_name -> matrixhub.v1alpha1.ReplicationPolicyType
	2,  // 7: matrixhub.v1alpha1.CreateReplicationRequest.trigger_type:type_name -> matrixhub.v1alpha1.triggerType
	4,  // 8: matrixhub.v1alpha1.CreateReplicationRequest.pull_base_policy:type_name -> matrixhub.v1alpha1.PullBasePolicy
	5,  // 9: matrixhub.v1alpha1.CreateReplicationRequest.push_base_policy:type_name -> matrixhub.v1alpha1.PushBasePolicy
	6,  // 10: matrixhub.v1alpha1.CreateReplicationResponse.replication:type_name -> matrixhub.v1alpha1.ReplicationItem
	2,  // 11: matrixhub.v1alpha1.UpdateReplicationRequest.trigger_type:type_name -> matrixhub.v1alpha1.triggerType
	4,  // 12: matrixhub.v1alpha1.UpdateReplicationRequest.pull_base_policy:type_name -> matrixhub.v1alpha1.PullBasePolicy
	5,  // 13: matrixhub.v1alpha1.UpdateReplicationRequest.push_base_policy:type_name -> matrixhub.v1alpha1.PushBasePolicy
	6,  // 14: matrixhub.v1alpha1.UpdateReplicationResponse.replication:type_name -> matrixhub.v1alpha1.ReplicationItem
	6,  // 15: matrixhub.v1alpha1.DeleteReplicationResponse.replication:type_name -> matrixhub.v1alpha1.ReplicationItem
	6,  // 16: matrixhub.v1alpha1.ListReplicationsResponse.replications:type_name -> matrixhub.v1alpha1.ReplicationItem
	22, // 17: matrixhub.v1alpha1.ListReplicationsResponse.pagination:type_name -> matrixhub.v1alpha1.Pagination
	2,  // 18: matrixhub.v1alpha1.ReplicationExecution.trigger_type:type_name -> matrixhub.v1alpha1.triggerType
	3,  // 19: matrixhub.v1alpha1.ReplicationExecution.status:type_name -> matrixhub.v1alpha1.ReplicationExecutionStatus
	17, // 20: matrixhub.v1alpha1.ListReplicationExecutionsResponse.executions:type_name -> matrixhub.v1alpha1.ReplicationExecution
	22, // 21: matrixhub.v1alpha1.ListReplicationExecutionsResponse.pagination:type_name -> matrixhub.v1alpha1.Pagination
	17, // 22: matrixhub.v1alpha1.StopReplicationExecutionResponse.execution:type_name -> matrixhub.v1alpha1.ReplicationExecution
	13, // 23: matrixhub.v1alpha1.Replication.ListReplications:input_type -> matrixhub.v1alpha1.ListReplicationsRequest
	7,  // 24: matrixhub.v1alpha1.Replication.CreateReplication:input_type -> matrixhub.v1alpha1.CreateReplicationRequest
	9,  // 25: matrixhub.v1alpha1.Replication.UpdateReplication:input_type -> matrixhub.v1alpha1.UpdateReplicationRequest
	11, // 26: matrixhub.v1alpha1.Replication.DeleteReplication:input_type -> matrixhub.v1alpha1.DeleteReplicationRequest
	15, // 27: matrixhub.v1alpha1.Replication.CreateReplicationExecution:input_type -> matrixhub.v1alpha1.CreateReplicationExecutionRequest
	18, // 28: matrixhub.v1alpha1.Replication.ListReplicationExecutions:input_type -> matrixhub.v1alpha1.ListReplicationExecutionsRequest
	20, // 29: matrixhub.v1alpha1.Replication.StopReplicationExecution:input_type -> matrixhub.v1alpha1.StopReplicationExecutionRequest
	14, // 30: matrixhub.v1alpha1.Replication.ListReplications:output_type -> matrixhub.v1alpha1.ListReplicationsResponse
	8,  // 31: matrixhub.v1alpha1.Replication.CreateReplication:output_type -> matrixhub.v1alpha1.CreateReplicationResponse
	10, // 32: matrixhub.v1alpha1.Replication.UpdateReplication:output_type -> matrixhub.v1alpha1.UpdateReplicationResponse
	12, // 33: matrixhub.v1alpha1.Replication.DeleteReplication:output_type -> matrixhub.v1alpha1.DeleteReplicationResponse
	16, // 34: matrixhub.v1alpha1.Replication.CreateReplicationExecution:output_type -> matrixhub.v1alpha1.CreateReplicationExecutionResponse
	19, // 35: matrixhub.v1alpha1.Replication.ListReplicationExecutions:output_type -> matrixhub.v1alpha1.ListReplicationExecutionsResponse
	21, // 36: matrixhub.v1alpha1.Replication.StopReplicationExecution:output_type -> matrixhub.v1alpha1.StopReplicationExecutionResponse
	30, // [30:37] is the sub-list for method output_type
	23, // [23:30] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_v1alpha1_replication_proto_init() }
func file_v1alpha1_replication_proto_init() {
	if File_v1alpha1_replication_proto != nil {
		return
	}
	file_v1alpha1_utils_proto_init()
	file_v1alpha1_replication_proto_msgTypes[2].OneofWrappers = []any{
		(*ReplicationItem_PullBasePolicy)(nil),
		(*ReplicationItem_PushBasePolicy)(nil),
	}
	file_v1alpha1_replication_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateReplicationRequest_PullBasePolicy)(nil),
		(*CreateReplicationRequest_PushBasePolicy)(nil),
	}
	file_v1alpha1_replication_proto_msgTypes[5].OneofWrappers = []any{
		(*UpdateReplicationRequest_PullBasePolicy)(nil),
		(*UpdateReplicationRequest_PushBasePolicy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_replication_proto_rawDesc), len(file_v1alpha1_replication_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_replication_proto_goTypes,
		DependencyIndexes: file_v1alpha1_replication_proto_depIdxs,
		EnumInfos:         file_v1alpha1_replication_proto_enumTypes,
		MessageInfos:      file_v1alpha1_replication_proto_msgTypes,
	}.Build()
	File_v1alpha1_replication_proto = out.File
	file_v1alpha1_replication_proto_goTypes = nil
	file_v1alpha1_replication_proto_depIdxs = nil
}
