// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1alpha1/replication.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PullBasePolicy with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PullBasePolicy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PullBasePolicy with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PullBasePolicyMultiError,
// or nil if none found.
func (m *PullBasePolicy) ValidateAll() error {
	return m.validate(true)
}

func (m *PullBasePolicy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SourceRegistryId

	// no validation rules for ResourceName

	// no validation rules for ResourceType

	// no validation rules for TargetResourceName

	if len(errors) > 0 {
		return PullBasePolicyMultiError(errors)
	}

	return nil
}

// PullBasePolicyMultiError is an error wrapping multiple validation errors
// returned by PullBasePolicy.ValidateAll() if the designated constraints
// aren't met.
type PullBasePolicyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PullBasePolicyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PullBasePolicyMultiError) AllErrors() []error { return m }

// PullBasePolicyValidationError is the validation error returned by
// PullBasePolicy.Validate if the designated constraints aren't met.
type PullBasePolicyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PullBasePolicyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PullBasePolicyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PullBasePolicyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PullBasePolicyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PullBasePolicyValidationError) ErrorName() string { return "PullBasePolicyValidationError" }

// Error satisfies the builtin error interface
func (e PullBasePolicyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPullBasePolicy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PullBasePolicyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PullBasePolicyValidationError{}

// Validate checks the field values on PushBasePolicy with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PushBasePolicy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushBasePolicy with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PushBasePolicyMultiError,
// or nil if none found.
func (m *PushBasePolicy) ValidateAll() error {
	return m.validate(true)
}

func (m *PushBasePolicy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ResourceName

	// no validation rules for ResourceType

	// no validation rules for TargetRegistryId

	// no validation rules for TargetResourceName

	if len(errors) > 0 {
		return PushBasePolicyMultiError(errors)
	}

	return nil
}

// PushBasePolicyMultiError is an error wrapping multiple validation errors
// returned by PushBasePolicy.ValidateAll() if the designated constraints
// aren't met.
type PushBasePolicyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushBasePolicyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushBasePolicyMultiError) AllErrors() []error { return m }

// PushBasePolicyValidationError is the validation error returned by
// PushBasePolicy.Validate if the designated constraints aren't met.
type PushBasePolicyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushBasePolicyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushBasePolicyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushBasePolicyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushBasePolicyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushBasePolicyValidationError) ErrorName() string { return "PushBasePolicyValidationError" }

// Error satisfies the builtin error interface
func (e PushBasePolicyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushBasePolicy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushBasePolicyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushBasePolicyValidationError{}

// Validate checks the field values on ReplicationItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ReplicationItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplicationItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReplicationItemMultiError, or nil if none found.
func (m *ReplicationItem) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplicationItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for PolicyType

	// no validation rules for TriggerType

	// no validation rules for Bandwidth

	// no validation rules for IsOverwrite

	// no validation rules for IsDisabled

	switch v := m.Policy.(type) {
	case *ReplicationItem_PullBasePolicy:
		if v == nil {
			err := ReplicationItemValidationError{
				field:  "Policy",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetPullBasePolicy()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ReplicationItemValidationError{
						field:  "PullBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ReplicationItemValidationError{
						field:  "PullBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPullBasePolicy()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ReplicationItemValidationError{
					field:  "PullBasePolicy",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ReplicationItem_PushBasePolicy:
		if v == nil {
			err := ReplicationItemValidationError{
				field:  "Policy",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetPushBasePolicy()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ReplicationItemValidationError{
						field:  "PushBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ReplicationItemValidationError{
						field:  "PushBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPushBasePolicy()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ReplicationItemValidationError{
					field:  "PushBasePolicy",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ReplicationItemMultiError(errors)
	}

	return nil
}

// ReplicationItemMultiError is an error wrapping multiple validation errors
// returned by ReplicationItem.ValidateAll() if the designated constraints
// aren't met.
type ReplicationItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplicationItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplicationItemMultiError) AllErrors() []error { return m }

// ReplicationItemValidationError is the validation error returned by
// ReplicationItem.Validate if the designated constraints aren't met.
type ReplicationItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplicationItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplicationItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplicationItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplicationItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplicationItemValidationError) ErrorName() string { return "ReplicationItemValidationError" }

// Error satisfies the builtin error interface
func (e ReplicationItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplicationItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplicationItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplicationItemValidationError{}

// Validate checks the field values on CreateReplicationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateReplicationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReplicationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReplicationRequestMultiError, or nil if none found.
func (m *CreateReplicationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReplicationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for PolicyType

	// no validation rules for TriggerType

	// no validation rules for Bandwidth

	// no validation rules for IsOverwrite

	switch v := m.Policy.(type) {
	case *CreateReplicationRequest_PullBasePolicy:
		if v == nil {
			err := CreateReplicationRequestValidationError{
				field:  "Policy",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetPullBasePolicy()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateReplicationRequestValidationError{
						field:  "PullBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateReplicationRequestValidationError{
						field:  "PullBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPullBasePolicy()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateReplicationRequestValidationError{
					field:  "PullBasePolicy",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *CreateReplicationRequest_PushBasePolicy:
		if v == nil {
			err := CreateReplicationRequestValidationError{
				field:  "Policy",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetPushBasePolicy()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateReplicationRequestValidationError{
						field:  "PushBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateReplicationRequestValidationError{
						field:  "PushBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPushBasePolicy()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateReplicationRequestValidationError{
					field:  "PushBasePolicy",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return CreateReplicationRequestMultiError(errors)
	}

	return nil
}

// CreateReplicationRequestMultiError is an error wrapping multiple validation
// errors returned by CreateReplicationRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateReplicationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReplicationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReplicationRequestMultiError) AllErrors() []error { return m }

// CreateReplicationRequestValidationError is the validation error returned by
// CreateReplicationRequest.Validate if the designated constraints aren't met.
type CreateReplicationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReplicationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReplicationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReplicationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReplicationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReplicationRequestValidationError) ErrorName() string {
	return "CreateReplicationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReplicationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReplicationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReplicationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReplicationRequestValidationError{}

// Validate checks the field values on CreateReplicationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateReplicationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReplicationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReplicationResponseMultiError, or nil if none found.
func (m *CreateReplicationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReplicationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetReplication()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateReplicationResponseValidationError{
					field:  "Replication",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateReplicationResponseValidationError{
					field:  "Replication",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReplication()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateReplicationResponseValidationError{
				field:  "Replication",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateReplicationResponseMultiError(errors)
	}

	return nil
}

// CreateReplicationResponseMultiError is an error wrapping multiple validation
// errors returned by CreateReplicationResponse.ValidateAll() if the
// designated constraints aren't met.
type CreateReplicationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReplicationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReplicationResponseMultiError) AllErrors() []error { return m }

// CreateReplicationResponseValidationError is the validation error returned by
// CreateReplicationResponse.Validate if the designated constraints aren't met.
type CreateReplicationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReplicationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReplicationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReplicationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReplicationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReplicationResponseValidationError) ErrorName() string {
	return "CreateReplicationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReplicationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReplicationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReplicationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReplicationResponseValidationError{}

// Validate checks the field values on UpdateReplicationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateReplicationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateReplicationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateReplicationRequestMultiError, or nil if none found.
func (m *UpdateReplicationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateReplicationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReplicationId

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for TriggerType

	// no validation rules for Bandwidth

	// no validation rules for IsOverwrite

	// no validation rules for IsDisabled

	switch v := m.Policy.(type) {
	case *UpdateReplicationRequest_PullBasePolicy:
		if v == nil {
			err := UpdateReplicationRequestValidationError{
				field:  "Policy",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetPullBasePolicy()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UpdateReplicationRequestValidationError{
						field:  "PullBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UpdateReplicationRequestValidationError{
						field:  "PullBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPullBasePolicy()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UpdateReplicationRequestValidationError{
					field:  "PullBasePolicy",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *UpdateReplicationRequest_PushBasePolicy:
		if v == nil {
			err := UpdateReplicationRequestValidationError{
				field:  "Policy",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetPushBasePolicy()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UpdateReplicationRequestValidationError{
						field:  "PushBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UpdateReplicationRequestValidationError{
						field:  "PushBasePolicy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPushBasePolicy()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UpdateReplicationRequestValidationError{
					field:  "PushBasePolicy",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return UpdateReplicationRequestMultiError(errors)
	}

	return nil
}

// UpdateReplicationRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateReplicationRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateReplicationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateReplicationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateReplicationRequestMultiError) AllErrors() []error { return m }

// UpdateReplicationRequestValidationError is the validation error returned by
// UpdateReplicationRequest.Validate if the designated constraints aren't met.
type UpdateReplicationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateReplicationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateReplicationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateReplicationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateReplicationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateReplicationRequestValidationError) ErrorName() string {
	return "UpdateReplicationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateReplicationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateReplicationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateReplicationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateReplicationRequestValidationError{}

// Validate checks the field values on UpdateReplicationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateReplicationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateReplicationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateReplicationResponseMultiError, or nil if none found.
func (m *UpdateReplicationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateReplicationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetReplication()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateReplicationResponseValidationError{
					field:  "Replication",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateReplicationResponseValidationError{
					field:  "Replication",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReplication()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateReplicationResponseValidationError{
				field:  "Replication",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateReplicationResponseMultiError(errors)
	}

	return nil
}

// UpdateReplicationResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateReplicationResponse.ValidateAll() if the
// designated constraints aren't met.
type UpdateReplicationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateReplicationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateReplicationResponseMultiError) AllErrors() []error { return m }

// UpdateReplicationResponseValidationError is the validation error returned by
// UpdateReplicationResponse.Validate if the designated constraints aren't met.
type UpdateReplicationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateReplicationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateReplicationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateReplicationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateReplicationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateReplicationResponseValidationError) ErrorName() string {
	return "UpdateReplicationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateReplicationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateReplicationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateReplicationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateReplicationResponseValidationError{}

// Validate checks the field values on DeleteReplicationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteReplicationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteReplicationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteReplicationRequestMultiError, or nil if none found.
func (m *DeleteReplicationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteReplicationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReplicationId

	if len(errors) > 0 {
		return DeleteReplicationRequestMultiError(errors)
	}

	return nil
}

// DeleteReplicationRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteReplicationRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteReplicationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteReplicationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteReplicationRequestMultiError) AllErrors() []error { return m }

// DeleteReplicationRequestValidationError is the validation error returned by
// DeleteReplicationRequest.Validate if the designated constraints aren't met.
type DeleteReplicationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteReplicationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteReplicationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteReplicationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteReplicationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteReplicationRequestValidationError) ErrorName() string {
	return "DeleteReplicationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteReplicationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteReplicationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteReplicationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteReplicationRequestValidationError{}

// Validate checks the field values on DeleteReplicationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteReplicationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteReplicationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteReplicationResponseMultiError, or nil if none found.
func (m *DeleteReplicationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteReplicationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetReplication()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeleteReplicationResponseValidationError{
					field:  "Replication",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeleteReplicationResponseValidationError{
					field:  "Replication",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReplication()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeleteReplicationResponseValidationError{
				field:  "Replication",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeleteReplicationResponseMultiError(errors)
	}

	return nil
}

// DeleteReplicationResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteReplicationResponse.ValidateAll() if the
// designated constraints aren't met.
type DeleteReplicationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteReplicationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteReplicationResponseMultiError) AllErrors() []error { return m }

// DeleteReplicationResponseValidationError is the validation error returned by
// DeleteReplicationResponse.Validate if the designated constraints aren't met.
type DeleteReplicationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteReplicationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteReplicationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteReplicationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteReplicationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteReplicationResponseValidationError) ErrorName() string {
	return "DeleteReplicationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteReplicationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteReplicationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteReplicationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteReplicationResponseValidationError{}

// Validate checks the field values on ListReplicationsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListReplicationsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReplicationsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListReplicationsRequestMultiError, or nil if none found.
func (m *ListReplicationsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReplicationsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for Search

	if len(errors) > 0 {
		return ListReplicationsRequestMultiError(errors)
	}

	return nil
}

// ListReplicationsRequestMultiError is an error wrapping multiple validation
// errors returned by ListReplicationsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListReplicationsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReplicationsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReplicationsRequestMultiError) AllErrors() []error { return m }

// ListReplicationsRequestValidationError is the validation error returned by
// ListReplicationsRequest.Validate if the designated constraints aren't met.
type ListReplicationsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReplicationsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReplicationsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReplicationsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReplicationsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReplicationsRequestValidationError) ErrorName() string {
	return "ListReplicationsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListReplicationsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReplicationsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReplicationsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReplicationsRequestValidationError{}

// Validate checks the field values on ListReplicationsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListReplicationsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReplicationsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListReplicationsResponseMultiError, or nil if none found.
func (m *ListReplicationsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReplicationsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetReplications() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListReplicationsResponseValidationError{
						field:  fmt.Sprintf("Replications[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListReplicationsResponseValidationError{
						field:  fmt.Sprintf("Replications[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListReplicationsResponseValidationError{
					field:  fmt.Sprintf("Replications[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListReplicationsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListReplicationsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListReplicationsResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListReplicationsResponseMultiError(errors)
	}

	return nil
}

// ListReplicationsResponseMultiError is an error wrapping multiple validation
// errors returned by ListReplicationsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListReplicationsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReplicationsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReplicationsResponseMultiError) AllErrors() []error { return m }

// ListReplicationsResponseValidationError is the validation error returned by
// ListReplicationsResponse.Validate if the designated constraints aren't met.
type ListReplicationsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReplicationsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReplicationsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReplicationsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReplicationsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReplicationsResponseValidationError) ErrorName() string {
	return "ListReplicationsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListReplicationsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReplicationsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReplicationsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReplicationsResponseValidationError{}

// Validate checks the field values on CreateReplicationExecutionRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *CreateReplicationExecutionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReplicationExecutionRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// CreateReplicationExecutionRequestMultiError, or nil if none found.
func (m *CreateReplicationExecutionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReplicationExecutionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReplicationId

	if len(errors) > 0 {
		return CreateReplicationExecutionRequestMultiError(errors)
	}

	return nil
}

// CreateReplicationExecutionRequestMultiError is an error wrapping multiple
// validation errors returned by
// CreateReplicationExecutionRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateReplicationExecutionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReplicationExecutionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReplicationExecutionRequestMultiError) AllErrors() []error { return m }

// CreateReplicationExecutionRequestValidationError is the validation error
// returned by CreateReplicationExecutionRequest.Validate if the designated
// constraints aren't met.
type CreateReplicationExecutionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReplicationExecutionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReplicationExecutionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReplicationExecutionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReplicationExecutionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReplicationExecutionRequestValidationError) ErrorName() string {
	return "CreateReplicationExecutionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReplicationExecutionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReplicationExecutionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReplicationExecutionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReplicationExecutionRequestValidationError{}

// Validate checks the field values on CreateReplicationExecutionResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *CreateReplicationExecutionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReplicationExecutionResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// CreateReplicationExecutionResponseMultiError, or nil if none found.
func (m *CreateReplicationExecutionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReplicationExecutionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreateReplicationExecutionResponseMultiError(errors)
	}

	return nil
}

// CreateReplicationExecutionResponseMultiError is an error wrapping multiple
// validation errors returned by
// CreateReplicationExecutionResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateReplicationExecutionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReplicationExecutionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReplicationExecutionResponseMultiError) AllErrors() []error { return m }

// CreateReplicationExecutionResponseValidationError is the validation error
// returned by CreateReplicationExecutionResponse.Validate if the designated
// constraints aren't met.
type CreateReplicationExecutionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReplicationExecutionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReplicationExecutionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReplicationExecutionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReplicationExecutionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReplicationExecutionResponseValidationError) ErrorName() string {
	return "CreateReplicationExecutionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReplicationExecutionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReplicationExecutionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReplicationExecutionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReplicationExecutionResponseValidationError{}

// Validate checks the field values on ReplicationExecution with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReplicationExecution) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplicationExecution with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReplicationExecutionMultiError, or nil if none found.
func (m *ReplicationExecution) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplicationExecution) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ReplicationId

	// no validation rules for TriggerType

	// no validation rules for Status

	// no validation rules for StartedTimestamp

	// no validation rules for CompletedTimestamp

	// no validation rules for TotalItems

	// no validation rules for SuccessfulItems

	if len(errors) > 0 {
		return ReplicationExecutionMultiError(errors)
	}

	return nil
}

// ReplicationExecutionMultiError is an error wrapping multiple validation
// errors returned by ReplicationExecution.ValidateAll() if the designated
// constraints aren't met.
type ReplicationExecutionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplicationExecutionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplicationExecutionMultiError) AllErrors() []error { return m }

// ReplicationExecutionValidationError is the validation error returned by
// ReplicationExecution.Validate if the designated constraints aren't met.
type ReplicationExecutionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplicationExecutionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplicationExecutionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplicationExecutionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplicationExecutionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplicationExecutionValidationError) ErrorName() string {
	return "ReplicationExecutionValidationError"
}

// Error satisfies the builtin error interface
func (e ReplicationExecutionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplicationExecution.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplicationExecutionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplicationExecutionValidationError{}

// Validate checks the field values on ListReplicationExecutionsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListReplicationExecutionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReplicationExecutionsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListReplicationExecutionsRequestMultiError, or nil if none found.
func (m *ListReplicationExecutionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReplicationExecutionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReplicationId

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for Search

	if len(errors) > 0 {
		return ListReplicationExecutionsRequestMultiError(errors)
	}

	return nil
}

// ListReplicationExecutionsRequestMultiError is an error wrapping multiple
// validation errors returned by
// ListReplicationExecutionsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListReplicationExecutionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReplicationExecutionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReplicationExecutionsRequestMultiError) AllErrors() []error { return m }

// ListReplicationExecutionsRequestValidationError is the validation error
// returned by ListReplicationExecutionsRequest.Validate if the designated
// constraints aren't met.
type ListReplicationExecutionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReplicationExecutionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReplicationExecutionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReplicationExecutionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReplicationExecutionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReplicationExecutionsRequestValidationError) ErrorName() string {
	return "ListReplicationExecutionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListReplicationExecutionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReplicationExecutionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReplicationExecutionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReplicationExecutionsRequestValidationError{}

// Validate checks the field values on ListReplicationExecutionsResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListReplicationExecutionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReplicationExecutionsResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ListReplicationExecutionsResponseMultiError, or nil if none found.
func (m *ListReplicationExecutionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReplicationExecutionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetExecutions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListReplicationExecutionsResponseValidationError{
						field:  fmt.Sprintf("Executions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListReplicationExecutionsResponseValidationError{
						field:  fmt.Sprintf("Executions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListReplicationExecutionsResponseValidationError{
					field:  fmt.Sprintf("Executions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListReplicationExecutionsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListReplicationExecutionsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListReplicationExecutionsResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListReplicationExecutionsResponseMultiError(errors)
	}

	return nil
}

// ListReplicationExecutionsResponseMultiError is an error wrapping multiple
// validation errors returned by
// ListReplicationExecutionsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListReplicationExecutionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReplicationExecutionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReplicationExecutionsResponseMultiError) AllErrors() []error { return m }

// ListReplicationExecutionsResponseValidationError is the validation error
// returned by ListReplicationExecutionsResponse.Validate if the designated
// constraints aren't met.
type ListReplicationExecutionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReplicationExecutionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReplicationExecutionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReplicationExecutionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReplicationExecutionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReplicationExecutionsResponseValidationError) ErrorName() string {
	return "ListReplicationExecutionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListReplicationExecutionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReplicationExecutionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReplicationExecutionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReplicationExecutionsResponseValidationError{}

// Validate checks the field values on StopReplicationExecutionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StopReplicationExecutionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StopReplicationExecutionRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// StopReplicationExecutionRequestMultiError, or nil if none found.
func (m *StopReplicationExecutionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StopReplicationExecutionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReplicationId

	// no validation rules for ExecutionId

	if len(errors) > 0 {
		return StopReplicationExecutionRequestMultiError(errors)
	}

	return nil
}

// StopReplicationExecutionRequestMultiError is an error wrapping multiple
// validation errors returned by StopReplicationExecutionRequest.ValidateAll()
// if the designated constraints aren't met.
type StopReplicationExecutionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StopReplicationExecutionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StopReplicationExecutionRequestMultiError) AllErrors() []error { return m }

// StopReplicationExecutionRequestValidationError is the validation error
// returned by StopReplicationExecutionRequest.Validate if the designated
// constraints aren't met.
type StopReplicationExecutionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StopReplicationExecutionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StopReplicationExecutionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StopReplicationExecutionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StopReplicationExecutionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StopReplicationExecutionRequestValidationError) ErrorName() string {
	return "StopReplicationExecutionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StopReplicationExecutionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStopReplicationExecutionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StopReplicationExecutionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StopReplicationExecutionRequestValidationError{}

// Validate checks the field values on StopReplicationExecutionResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *StopReplicationExecutionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StopReplicationExecutionResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// StopReplicationExecutionResponseMultiError, or nil if none found.
func (m *StopReplicationExecutionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *StopReplicationExecutionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetExecution()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StopReplicationExecutionResponseValidationError{
					field:  "Execution",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StopReplicationExecutionResponseValidationError{
					field:  "Execution",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExecution()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StopReplicationExecutionResponseValidationError{
				field:  "Execution",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return StopReplicationExecutionResponseMultiError(errors)
	}

	return nil
}

// StopReplicationExecutionResponseMultiError is an error wrapping multiple
// validation errors returned by
// StopReplicationExecutionResponse.ValidateAll() if the designated
// constraints aren't met.
type StopReplicationExecutionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StopReplicationExecutionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StopReplicationExecutionResponseMultiError) AllErrors() []error { return m }

// StopReplicationExecutionResponseValidationError is the validation error
// returned by StopReplicationExecutionResponse.Validate if the designated
// constraints aren't met.
type StopReplicationExecutionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StopReplicationExecutionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StopReplicationExecutionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StopReplicationExecutionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StopReplicationExecutionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StopReplicationExecutionResponseValidationError) ErrorName() string {
	return "StopReplicationExecutionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e StopReplicationExecutionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStopReplicationExecutionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StopReplicationExecutionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StopReplicationExecutionResponseValidationError{}
