// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/role.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectRoleType int32

const (
	ProjectRoleType_ROLE_TYPE_PROJECT_ADMIN  ProjectRoleType = 0
	ProjectRoleType_ROLE_TYPE_PROJECT_EDITOR ProjectRoleType = 1
	ProjectRoleType_ROLE_TYPE_PROJECT_VIEWER ProjectRoleType = 2
)

// Enum value maps for ProjectRoleType.
var (
	ProjectRoleType_name = map[int32]string{
		0: "ROLE_TYPE_PROJECT_ADMIN",
		1: "ROLE_TYPE_PROJECT_EDITOR",
		2: "ROLE_TYPE_PROJECT_VIEWER",
	}
	ProjectRoleType_value = map[string]int32{
		"ROLE_TYPE_PROJECT_ADMIN":  0,
		"ROLE_TYPE_PROJECT_EDITOR": 1,
		"ROLE_TYPE_PROJECT_VIEWER": 2,
	}
)

func (x ProjectRoleType) Enum() *ProjectRoleType {
	p := new(ProjectRoleType)
	*p = x
	return p
}

func (x ProjectRoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectRoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_role_proto_enumTypes[0].Descriptor()
}

func (ProjectRoleType) Type() protoreflect.EnumType {
	return &file_v1alpha1_role_proto_enumTypes[0]
}

func (x ProjectRoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectRoleType.Descriptor instead.
func (ProjectRoleType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_role_proto_rawDescGZIP(), []int{0}
}

var File_v1alpha1_role_proto protoreflect.FileDescriptor

const file_v1alpha1_role_proto_rawDesc = "" +
	"\n" +
	"\x13v1alpha1/role.proto\x12\x12matrixhub.v1alpha1*j\n" +
	"\x0fProjectRoleType\x12\x1b\n" +
	"\x17ROLE_TYPE_PROJECT_ADMIN\x10\x00\x12\x1c\n" +
	"\x18ROLE_TYPE_PROJECT_EDITOR\x10\x01\x12\x1c\n" +
	"\x18ROLE_TYPE_PROJECT_VIEWER\x10\x02B<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_role_proto_rawDescOnce sync.Once
	file_v1alpha1_role_proto_rawDescData []byte
)

func file_v1alpha1_role_proto_rawDescGZIP() []byte {
	file_v1alpha1_role_proto_rawDescOnce.Do(func() {
		file_v1alpha1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_role_proto_rawDesc), len(file_v1alpha1_role_proto_rawDesc)))
	})
	return file_v1alpha1_role_proto_rawDescData
}

var file_v1alpha1_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1alpha1_role_proto_goTypes = []any{
	(ProjectRoleType)(0), // 0: matrixhub.v1alpha1.ProjectRoleType
}
var file_v1alpha1_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1alpha1_role_proto_init() }
func file_v1alpha1_role_proto_init() {
	if File_v1alpha1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_role_proto_rawDesc), len(file_v1alpha1_role_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1alpha1_role_proto_goTypes,
		DependencyIndexes: file_v1alpha1_role_proto_depIdxs,
		EnumInfos:         file_v1alpha1_role_proto_enumTypes,
	}.Build()
	File_v1alpha1_role_proto = out.File
	file_v1alpha1_role_proto_goTypes = nil
	file_v1alpha1_role_proto_depIdxs = nil
}
